# Generated by Django 4.2 on 2023-09-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0004_resume_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="coverletter",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="cover_letters/"),
        ),
    ]
