# Generated by Django 4.2 on 2023-09-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0005_coverletter_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverletter",
            name="job_post",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="web_app.jobpost"),
        ),
    ]
