# Generated by Django 4.2.5 on 2023-09-26 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web_app", "0006_alter_coverletter_job_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
