# Generated by Django 4.2.5 on 2023-09-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0007_alter_resume_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="coverletter",
            name="filename",
            field=models.CharField(default="Cover_Letter", max_length=255),
        ),
    ]
