# Generated by Django 4.2.5 on 2023-10-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0011_remove_job_link_alter_job_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_overview_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
